services:
  clickhouse-server:
    container_name: lugx-gaming-clickhouse-server
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      - ./init:/docker-entrypoint-initdb.d

volumes:
  clickhouse-data:
  clickhouse-logs: