apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lugx-gaming-clickhouse-pvc
spec:
  storageClassName: ebs-sc-automode
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-gaming-clickhouse-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-gaming
      tier: clickhouse
  template:
    metadata:
      labels:
        app: lugx-gaming
        tier: clickhouse
    spec:
      containers:
        - name: clickhouse-server
          image: clickhouse/clickhouse-server:latest
          ports:
            - containerPort: 8123
            - containerPort: 9004
          env:
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-clickhouse-credentials-secret
                  key: CLICKHOUSE_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - name: clickhouse-storage
              mountPath: /var/lib/clickhouse
            - name: clickhouse-init-script
              mountPath: /docker-entrypoint-initdb.d
            - name: clickhouse-mysql-interface
              mountPath: /etc/clickhouse-server/conf.d
            - name: clickhouse-mysql-user
              mountPath: /etc/clickhouse-server/users.d/mysql_user.xml
              subPath: mysql_user.xml
      volumes:
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: lugx-gaming-clickhouse-pvc
        - name: clickhouse-init-script
          configMap:
            name: lugx-gaming-clickhouse-init-configmap
        - name: clickhouse-mysql-interface
          configMap:
            name: lugx-gaming-clickhouse-mysql-interface-configmap
        - name: clickhouse-mysql-user
          configMap:
            name: lugx-gaming-clickhouse-mysql-user-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: lugx-gaming-clickhouse-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: lugx-gaming
    tier: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30084
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: lugx-gaming-clickhouse-mysql-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: lugx-gaming
    tier: clickhouse
  ports:
    - protocol: TCP
      port: 9004
      targetPort: 9004
      nodePort: 30085
  type: LoadBalancer