apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-gaming-frontend-deployment
  labels:
    app: lugx-gaming
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-gaming
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lugx-gaming
        tier: frontend
    spec:
      containers:
        - name: lugx-gaming-frontend
          image: kaneeldias/lugx-gaming-frontend:hello
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: lugx-gaming-frontend-service
  labels:
    app: lugx-gaming
    tier: frontend
spec:
  selector:
    app: lugx-gaming
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort