apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-gaming-games-service-api-deployment
  labels:
    app: lugx-gaming
    tier: games-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-gaming
      tier: games-service-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lugx-gaming
        tier: games-service-api
    spec:
      containers:
        - name: lugx-gaming-games-service-api
          image: kaneeldias/lugx-gaming-games-service-api:e2af53b
          env:
            - name: TAG
              value: "latest"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-database-credentials-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-database-credentials-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "lugx-gaming-database-service"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-database-credentials-secret
                  key: POSTGRES_DB
            - name: GIN_MODE
              value: "release"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "8Mi"
              cpu: "10m"
            limits:
              memory: "8Mi"
              cpu: "10m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: lugx-gaming-games-service-api-service
  labels:
    app: lugx-gaming
    tier: games-service-api
spec:
  selector:
    app: lugx-gaming
    tier: games-service-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30081
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lugx-gaming-games-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lugx-gaming-games-service-api-deployment

  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80