apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-gaming-frontend-deployment
  labels:
    app: lugx-gaming
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-gaming
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lugx-gaming
        tier: frontend
    spec:
      containers:
        - name: lugx-gaming-frontend
          image: kaneeldias/lugx-gaming-frontend:eb200fb
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "8Mi"
              cpu: "10m"
            limits:
              memory: "8Mi"
              cpu: "10m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: lugx-gaming-frontend-service
  labels:
    app: lugx-gaming
    tier: frontend
spec:
  selector:
    app: lugx-gaming
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lugx-gaming-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lugx-gaming-frontend-deployment

  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80