apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-gaming-analytics-service-api-deployment
  labels:
    app: lugx-gaming
    tier: analytics-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-gaming
      tier: analytics-service-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lugx-gaming
        tier: analytics-service-api
    spec:
      containers:
        - name: lugx-gaming-analytics-service-api
          image: kaneeldias/lugx-gaming-analytics-service-api:575a164
          env:
            - name: TAG
              value: "latest"
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-clickhouse-credentials-secret
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_HOST
              value: "lugx-gaming-clickhouse-service"
            - name: CLICKHOUSE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-clickhouse-credentials-secret
                  key: CLICKHOUSE_DATABASE
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: GIN_MODE
              value: "release"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: lugx-gaming-analytics-service-api-service
  labels:
    app: lugx-gaming
    tier: analytics-service-api
spec:
  selector:
    app: lugx-gaming
    tier: analytics-service-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30083
  type: NodePort