apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lugx-gaming-database-pvc
spec:
  storageClassName: ebs-sc-automode
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-gaming-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-gaming
      tier: database
  template:
    metadata:
      labels:
        app: lugx-gaming
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-database-credentials-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-database-credentials-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: lugx-gaming-database-credentials-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: lugx-gaming-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lugx-gaming-database-service
spec:
  type: ClusterIP
  selector:
    app: lugx-gaming
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
