apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-automode
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3