name: Update order service image and deploy

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "The tag of the Docker image to be used"
        required: true
        default: "latest"
  repository_dispatch:
    types: [ update-order-image-and-deploy ]

jobs:
  change-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine image tag
        id: determine-tag
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "image-tag=${{ github.event.client_payload.image-tag }}" >> $GITHUB_ENV
          else
            echo "image-tag=${{ github.event.inputs.image-tag }}" >> $GITHUB_ENV
          fi

      - name: Change image tag in deployment file
        run: |
          sed -i "s|image: kaneeldias/lugx-gaming-order-service-api:.*|image: kaneeldias/lugx-gaming-order-service-api:${{ env.image-tag }}|g" lugx-gaming-order-service-api.yml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update order service image tag to ${{ env.image-tag }}"
          branch: master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl and EKS context
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}

      - name: Apply Kubernetes manifest
        run: |
          kubectl apply -f lugx-gaming-order-service-api.yml && kubectl rollout restart deployment/lugx-gaming-order-service-api-deployment
